### ISSUE TITLE
App icon not hiding itself after activation.

### ISSUE THREAD

**Issue by MillionsToOne** [DavidBerdik/Let-Me-Downgrade#7]
After rebooting the device and enabling app downgrade in QS, the app closes, but doesn't hide the app icon which worked on previous releases. It annoys me that I have an app icon in my app drawer sitting like a duck, which just opens app settings

**Comment by DavidBerdik** [comment]
Could you please check your LSPosed settings to see if the "Force apps to show launcher icons" toggle is turned on or off as shown in the screenshot below? If it is toggled on as it is in the screenshot, try toggling it off and reboot your phone. After your phone is rebooted, the icon should disappear soon after the next time you use the Quick Settings Tile.

Although I believe that this will solve your problem, please let me know if it does not so that I may do some further investigation into the problem.

![Screenshot_20231104-165304](https://github.com/DavidBerdik/Let-Me-Downgrade/assets/7663225/08eeeb22-6322-448a-b321-51bb41ac344e)

**Comment by MillionsToOne** [comment]
It did disappear. I didn't even know why that toggle was on in the first place since I always turn it off. Will be closing now

**Comment by DavidBerdik** [comment]
Great! I believe it was caused by an LSPosed update, as I also always turn it off and was surprised to find mine toggled on as well.
